items:

  - type: plain
    itemId: minecraft:map
    slotId: 53
    displayName: 所持金：

  - type: select
    itemId: mmorpg:tp_back
    slotId: 3
    displayName: null
    price: 500

  - type: select
    itemId: mmorpg:map
    slotId: 5
    displayName: null
    price: 100

  - type: select
    itemId: mmorpg:potions/full_reset_talent
    slotId: 11
    displayName: null
    price: 0

  - type: select
    itemId: mmorpg:potions/full_reset_spell
    slotId: 12
    displayName: null
    price: 0

  - type: select
    itemId: mmorpg:potions/full_reset_passive
    slotId: 13
    displayName: null
    price: 0

  - type: select
    itemId: mmorpg:potions/full_reset_ascendancy
    slotId: 14
    displayName: null
    price: 0

  - type: select
    itemId: mmorpg:potions/full_reset_stat
    slotId: 15
    displayName: null
    price: 0

  - type: select
    itemId: mmorpg:master_bag
    slotId: 22
    displayName: null
    price: 3000

  - type: select
    itemId: mmorpg:potion/health/5
    slotId: 39
    displayName: null
    price: 500

  - type: select
    itemId: mmorpg:potion/resource/5
    slotId: 41
    displayName: null
    price: 500

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 45
    displayName:  

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 46
    displayName:  

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 47
    displayName:  
  
  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 48
    displayName:  

  - type: transition
    itemId: minecraft:red_bed
    slotId: 49
    displayName: ホームに戻る
    next: mode

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 50
    displayName:  

  - type: transition
    itemId: minecraft:firework_rocket
    slotId: 51
    displayName: 次のページ
    next: buy_page2

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 52
    displayName:  
