items:

  - type: plain
    itemId: minecraft:map
    slotId: 53
    displayName: 所持金：

  - type: select
    itemId: mmorpg:tp_back
    slotId: 1
    displayName: null
    price: 100

  - type: select
    itemId: mmorpg:tp_back
    slotId: 2
    displayName: null
    price: 100

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 45
    displayName: null

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 46
    displayName: null

  - type: transition
    itemId: minecraft:red_bed
    slotId: 47
    displayName: 戻る
    next: mode

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 48
    displayName: null

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 49
    displayName: null

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 50
    displayName: null

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 51
    displayName: null

  - type: plain
    itemId: minecraft:gray_stained_glass_pane
    slotId: 52
    displayName: null
