items:

  - type: plain
    itemId: minecraft:map
    slotId: 53
    displayName: 所持金：

  - type: transition
    itemId: minecraft:diamond_sword
    slotId: 24
    displayName: 購入
    next: buy_page1

  - type: transition
    itemId: minecraft:emerald
    slotId: 20
    displayName: 売却
    next: sell
